// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIkuyc-f0sWnsQufcyHjM9iKeXvtJYTM',
    appId: '1:718903259227:web:0e3481d250eb96d4aacf7e',
    messagingSenderId: '718903259227',
    projectId: 'thrillfit-e1100',
    authDomain: 'thrillfit-e1100.firebaseapp.com',
    storageBucket: 'thrillfit-e1100.appspot.com',
    measurementId: 'G-9R975HKRMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2YngiVZXhHtWv4QiHmtFRk17EQ-n0iU',
    appId: '1:718903259227:android:2daa5e2120a70ac8aacf7e',
    messagingSenderId: '718903259227',
    projectId: 'thrillfit-e1100',
    storageBucket: 'thrillfit-e1100.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDviTJojMDm9KJ1vRkNTUqrM_aeJCT1ZR0',
    appId: '1:718903259227:ios:bbcfe2590990acedaacf7e',
    messagingSenderId: '718903259227',
    projectId: 'thrillfit-e1100',
    storageBucket: 'thrillfit-e1100.appspot.com',
    iosBundleId: 'com.thrill.fit.thrillFit',
  );
}
